name: Build and Push Latest MongoDB Docker Image

on:
  push:
    branches: [ main ]

jobs:
  # SpectralLint:
  #   name: SpectralLint
  #   runs-on: ubuntu-latest
  #   steps:
  #    - uses: actions/checkout@v2
  #    - name: Install Spectral
  #      run: npm install -g spectral
  #    - name: Lint OpenAPI files
  #      uses: stoplightio/spectral-action@latest
  #      with:
  #        file_glob: "./openapi.yaml"
  #        spectral_ruleset: ./.spectral.yaml

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start SSH agent
        id: ssh-agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUBTOKEN }}

      - name: Build and tag image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/mongo:latest .

      - name: Push image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/mongo:latest
      
